"""Initial migration

Revision ID: ba76339aa64b
Revises: e08e2a8c36bc
Create Date: 2025-05-05 08:18:58.519833

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba76339aa64b'
down_revision = 'e08e2a8c36bc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
